
font:
  size: 10
  faceName: Arial
  family: 74
  weight: 400

about:
  version:
    text: "Ver.1.0.0"
    fontSize: 16
    weight: 400
  introduce:
    text: "iDIA-QC is a Python Graphical User Interface (GUI) for a suite of analytical tools enabling comprehensive evaluation and analysis of the quality of mass spectrometry-based DIA files. The software incorporates the protein qualitative and quantitative algorithms from DIA-NN and uses msConvert for file conversion to extracted precursor ion chromatogram (PIC). Based on 15 metrics extracted from the DIA files, which describe the characteristics of the raw files from timsTOF serial instruments, TripleTOF instruments, and Orbitrap serial instruments, we utilize machine learning models to predict the quality of the DIA files. The outputs of iDIA-QC in a longitudinal summary, visually display the quality of the DIA files. Additionally, it promptly shares the prediction results and visualization with administrators via email."
    fontSize: 12
    weight: 400

help:
  text: 'help的文本描述'

setting:
  pkl: './config/setting.pkl'

notify:
  mail_host: smtp-mail.outlook.com
  mail_user: iDIAQC@outlook.com
  mail_pass: Guomics@123456

inst: ['TripleTOF 5600', 'TripleTOF 6600', 'Q Exactive', 'Q Exactive Plus', 'Q Exactive HF', 'Q Exactive HF-X', 'Exploris 480', 'timsTOF Pro']